### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by TheoGuyard** [TheoGuyard/benchmark_sparse_support_recovery#8]
This issue gathers the next tasks to address with this benchmark. Feel free to edit it 👍

### Objective
- [ ] Reflexion on new metrics to display. For MEG, it can be interesting to measure the distance to the real support for instance.

### Datasets
- [ ] Add a MEG dataset
- [ ] Add a pattern recognition dataset
- [ ] Add some ML datasets with available ground truth
- [ ] Add some finance dataset

> Keep in mind that we are interested in datasets where the ground truth is available to be able to compute relevant statistics.

### Solvers
- [ ] Find an (or several) efficient and **open-source** solver for the exact resolution of L0-problems
- [ ] Test the three strategies "L0", "L0L1" and "L0L2" in `l0learn` and not only "L0"
- [ ] Add solvers from `skglm`
